const DEFAULT_BUILDING_VISUAL = {
  model_id: "hq_01",
  color: 0xffffff,
  emissive: 0x17345e,
  emissiveIntensity: 0.08,
  scale: 5
};

const trade = ({ enabled = false, trade_table_id = null, handling_speed = 0, cargo_capacity = 0, min_reputation = 0 } = {}) => ({
  enabled,
  trade_table_id,
  handling_speed,
  cargo_capacity,
  min_reputation
});

const docking = (capacity) => ({ capacity });

const sectorAnchor = (radius = null) => ({
  type: "sector_anchor",
  radius
});

const freeSpace = () => ({
  type: "free_space"
});

const resourceNode = (required_resource_type) => ({
  type: "resource_node",
  required_resource_type
});

export const BUILDING_DEFINITIONS = {
  arc_station: {
    building_id: "arc_station",
    name: "아크 스테이션",
    name_en: "Arc Station",
    size: "전용",
    category: "헤드쿼터",
    hp: 1000,
    admin_cost: 20,
    placement_rule: sectorAnchor(null),
    base_production: { power: true, beta_crystal: true },
    production: { worker: true },
    polity_resource: { population: true },
    docking: docking(null),
    trade: trade({ enabled: true, trade_table_id: "trade_basic", handling_speed: 2.0, cargo_capacity: 100000 }),
    default_polity_id: "asta",
    initial_inventory: {
      item_001: 5000,
      item_004: 3000,
      item_003: 2000,
      item_002: 1500,
      item_007: 4000,
      item_008: 2000
    },
    visual: { ...DEFAULT_BUILDING_VISUAL, scale: 5.5 },
    description: "기본 인구수 제공, 함선 정박, 자체 방어시스템, 창고, 자체 전기에너지 생산(자동), 자체 생존자원 생산(자동)."
  },
  plasma_power_plant: {
    building_id: "plasma_power_plant",
    name: "플라즈마 파워 플랜트",
    name_en: "Plasma Power Plant",
    size: "대형",
    category: "발전소",
    hp: 1000,
    admin_cost: 15,
    placement_rule: sectorAnchor(320),
    base_production: { power: true },
    production: {},
    polity_resource: {},
    docking: docking(0),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL },
    description: "전기를 생산하는 시설"
  },
  beta_particle_reactor: {
    building_id: "beta_particle_reactor",
    name: "베타 입자 리액터",
    name_en: "Beta Particle Reactor",
    size: "대형",
    category: "하이퍼드라이브 에너지 생산시설",
    hp: 1000,
    admin_cost: 15,
    placement_rule: freeSpace(),
    base_production: { beta_crystal: true },
    production: {},
    polity_resource: {},
    docking: docking(0),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL },
    description: "하이퍼드라이브 에너지를 생산하는 시설"
  },
  orbital_dorm: {
    building_id: "orbital_dorm",
    name: "궤도 거주지",
    name_en: "Orbital Dorm",
    size: "대형",
    category: "거주시설",
    hp: 1000,
    admin_cost: 10,
    placement_rule: sectorAnchor(640),
    base_production: {},
    production: { worker: true },
    polity_resource: { population: true },
    docking: docking(0),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL },
    description: "인구와 노동자 제공. 노동자는 시설로 출퇴근하여 건물의 생산활동을 촉진한다."
  },
  colony_dorm: {
    building_id: "colony_dorm",
    name: "외곽 거주지",
    name_en: "Colony Dorm",
    size: "대형",
    category: "거주시설",
    hp: 1000,
    admin_cost: 4,
    placement_rule: freeSpace(),
    base_production: {},
    production: { worker: true },
    polity_resource: { population: true },
    docking: docking(0),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL },
    description: "인구와 노동자 제공. 노동자는 시설로 출퇴근하여 건물의 생산활동을 촉진한다."
  },
  orbital_defence_turret: {
    building_id: "orbital_defence_turret",
    name: "궤도 방어 터렛",
    name_en: "Orbital Defence Turret",
    size: "소형",
    category: "방어 포탑",
    hp: 1000,
    admin_cost: 2,
    placement_rule: sectorAnchor(640),
    base_production: {},
    production: {},
    polity_resource: {},
    docking: docking(0),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL, scale: 3.5 },
    description: "적대적 함선을 공격하는 방어터렛 시설"
  },
  sentinel_turret: {
    building_id: "sentinel_turret",
    name: "감시 터렛",
    name_en: "Sentinel Turret",
    size: "소형",
    category: "방어 포탑",
    hp: 1000,
    admin_cost: 0,
    placement_rule: freeSpace(),
    base_production: {},
    production: {},
    polity_resource: {},
    docking: docking(0),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL, scale: 3.5 },
    description: "적대적 함선을 공격하는 방어터렛 시설"
  },
  shipyard: {
    building_id: "shipyard",
    name: "조선소",
    name_en: "Shipyard",
    size: "대형",
    category: "조선소",
    hp: 1000,
    admin_cost: 18,
    placement_rule: freeSpace(),
    base_production: {},
    production: { ship: true },
    polity_resource: {},
    docking: docking(null),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL },
    description: "다양한 규격의 함선을 건조하고 파손된 선체를 수리하는 대형 도크 시설."
  },
  trade_port: {
    building_id: "trade_port",
    name: "무역항",
    name_en: "Trade Port",
    size: "대형",
    category: "거래소",
    hp: 1000,
    admin_cost: 15,
    placement_rule: freeSpace(),
    base_production: {},
    production: {},
    polity_resource: { building_maintenance_reduction: true },
    docking: docking(null),
    trade: trade({ enabled: true, trade_table_id: "trade_basic", handling_speed: 3.0, cargo_capacity: 200000 }),
    default_polity_id: "asta",
    visual: { ...DEFAULT_BUILDING_VISUAL },
    description: "외부 함선이 정박하여 물자를 거래하는 경제 허브. 상업 활동과 보급의 중심지."
  },
  outbase: {
    building_id: "outbase",
    name: "아웃베이스",
    name_en: "Outbase",
    size: "대형",
    category: "전초기지",
    hp: 1000,
    admin_cost: 0,
    placement_rule: freeSpace(),
    base_production: {},
    production: {},
    polity_resource: {},
    docking: docking(5),
    trade: trade({ enabled: true, trade_table_id: "trade_basic", handling_speed: 1.0, cargo_capacity: 50000 }),
    default_polity_id: "asta",
    initial_inventory: {
      item_001: 2000,
      item_004: 1500,
      item_003: 1000,
      item_007: 1500
    },
    visual: { ...DEFAULT_BUILDING_VISUAL },
    description: "섹터 확장을 위한 다목적 전초기지. 소규모 방어와 보급 능력을 동시에 갖춤."
  },
  hydro_synthesizer: {
    building_id: "hydro_synthesizer",
    name: "수자원 합성소",
    name_en: "Hydro-Synthesizer",
    size: "중형",
    category: "자원 생산 시설",
    hp: 1000,
    admin_cost: 2,
    placement_rule: resourceNode("hydrite_mineral"),
    base_production: {},
    production: { water: true },
    polity_resource: { happiness: true },
    docking: docking(0),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL, scale: 4.5 },
    description: "수소 합성 및 폐수 재활용 하이브리드 정수장. 깨끗한 식수를 공급."
  },
  mine: {
    building_id: "mine",
    name: "광산",
    name_en: "Mine",
    size: "중형",
    category: "자원 생산 시설",
    hp: 1000,
    admin_cost: 0,
    placement_rule: resourceNode("mineral"),
    base_production: {},
    production: { mineral: true },
    polity_resource: {},
    docking: docking(0),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL, scale: 4.5 },
    description: "행성 지각의 유용 광물을 시추하고 1차 채굴을 수행하는 산업 시설."
  },
  refinery: {
    building_id: "refinery",
    name: "정제소",
    name_en: "Refinery",
    size: "중형",
    category: "자원 생산 시설",
    hp: 1000,
    admin_cost: 0,
    placement_rule: resourceNode("gas"),
    base_production: {},
    production: { gas: true },
    polity_resource: {},
    docking: docking(0),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL, scale: 4.5 },
    description: "가스전으로부터 고에너지 기체를 추출하고 불순물을 제거하는 가스 정제 시설."
  },
  bio_fab: {
    building_id: "bio_fab",
    name: "바이오 팹",
    name_en: "Bio Fab",
    size: "중형",
    category: "자원 생산 시설",
    hp: 1000,
    admin_cost: 0,
    placement_rule: freeSpace(),
    base_production: {},
    production: { bio: true },
    polity_resource: { happiness: true },
    docking: docking(0),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL, scale: 4.5 },
    description: "수경 재배와 세포 배양 기술을 이용해 식품 및 의약품의 원료인 유기 자원을 생산."
  },
  food_factory: {
    building_id: "food_factory",
    name: "식품 공장",
    name_en: "Food Factory",
    size: "중형",
    category: "공장",
    hp: 1000,
    admin_cost: 1,
    placement_rule: freeSpace(),
    base_production: {},
    production: { food: true },
    polity_resource: { happiness: true },
    docking: docking(0),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL, scale: 4.5 },
    description: "바이오 자원을 가공하여 거주민들이 즉시 소비할 수 있는 영양 식품을 제조."
  },
  silicon_factory: {
    building_id: "silicon_factory",
    name: "반도체 공장",
    name_en: "Silicon Factory",
    size: "중형",
    category: "공장",
    hp: 1000,
    admin_cost: 1,
    placement_rule: freeSpace(),
    base_production: {},
    production: { material: true },
    polity_resource: {},
    docking: docking(0),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL, scale: 4.5 },
    description: "정제된 광물 자원을 투입하여 기지 현대화와 함선 제작에 필수적인 반도체 생산."
  },
  weapon_factory: {
    building_id: "weapon_factory",
    name: "무기 공장",
    name_en: "Weapon Factory",
    size: "중형",
    category: "공장",
    hp: 1000,
    admin_cost: 2,
    placement_rule: freeSpace(),
    base_production: {},
    production: { weapon: true },
    polity_resource: {},
    docking: docking(0),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL, scale: 4.5 },
    description: "금속과 반도체를 결합하여 함선 전용 미사일, 레이저 포 등 표준 무기 체계 생산."
  },
  advanced_weapon_factory: {
    building_id: "advanced_weapon_factory",
    name: "특수 무기 공장",
    name_en: "Advanced Weapon Factory",
    size: "중형",
    category: "공장",
    hp: 1000,
    admin_cost: 3,
    placement_rule: freeSpace(),
    base_production: {},
    production: { weapon: true },
    polity_resource: {},
    docking: docking(0),
    trade: trade(),
    visual: { ...DEFAULT_BUILDING_VISUAL, scale: 4.5 },
    description: "희귀 자원과 고농축 에너지를 사용하여 실험적인 프로토타입 및 특수 병기 제조."
  }
};

export const BUILDING_IDS = Object.keys(BUILDING_DEFINITIONS);
